# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17protobufs/service.proto\x12\x0b\x66ileSharing\".\n\x0cLoginRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\r\n\x05items\x18\x02 \x03(\t\"1\n\rLoginResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\" \n\rLogoutRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"2\n\x0eLogoutResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1f\n\x0fTransferRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"4\n\x10TransferResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\".\n\rUploadRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"/\n\x0eUploadResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0c\n\x04name\x18\x02 \x01(\t\".\n\x0cTableRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\r\n\x05items\x18\x02 \x03(\t\"1\n\rTableResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1e\n\x0bPingRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"\x1f\n\x0cPingResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32P\n\x0cLoginService\x12@\n\x05Login\x12\x19.fileSharing.LoginRequest\x1a\x1a.fileSharing.LoginResponse\"\x00\x32T\n\rLogoutService\x12\x43\n\x06Logout\x12\x1a.fileSharing.LogoutRequest\x1a\x1b.fileSharing.LogoutResponse\"\x00\x32\\\n\x0fTransferService\x12I\n\x08Transfer\x12\x1c.fileSharing.TransferRequest\x1a\x1d.fileSharing.TransferResponse\"\x00\x32T\n\rUploadService\x12\x43\n\x06Upload\x12\x1a.fileSharing.UploadRequest\x1a\x1b.fileSharing.UploadResponse\"\x00\x32P\n\x0cTableService\x12@\n\x05Table\x12\x19.fileSharing.TableRequest\x1a\x1a.fileSharing.TableResponse\"\x00\x32L\n\x0bPingService\x12=\n\x04Ping\x12\x18.fileSharing.PingRequest\x1a\x19.fileSharing.PingResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobufs.service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOGINREQUEST']._serialized_start=40
  _globals['_LOGINREQUEST']._serialized_end=86
  _globals['_LOGINRESPONSE']._serialized_start=88
  _globals['_LOGINRESPONSE']._serialized_end=137
  _globals['_LOGOUTREQUEST']._serialized_start=139
  _globals['_LOGOUTREQUEST']._serialized_end=171
  _globals['_LOGOUTRESPONSE']._serialized_start=173
  _globals['_LOGOUTRESPONSE']._serialized_end=223
  _globals['_TRANSFERREQUEST']._serialized_start=225
  _globals['_TRANSFERREQUEST']._serialized_end=256
  _globals['_TRANSFERRESPONSE']._serialized_start=258
  _globals['_TRANSFERRESPONSE']._serialized_end=310
  _globals['_UPLOADREQUEST']._serialized_start=312
  _globals['_UPLOADREQUEST']._serialized_end=358
  _globals['_UPLOADRESPONSE']._serialized_start=360
  _globals['_UPLOADRESPONSE']._serialized_end=407
  _globals['_TABLEREQUEST']._serialized_start=409
  _globals['_TABLEREQUEST']._serialized_end=455
  _globals['_TABLERESPONSE']._serialized_start=457
  _globals['_TABLERESPONSE']._serialized_end=506
  _globals['_PINGREQUEST']._serialized_start=508
  _globals['_PINGREQUEST']._serialized_end=538
  _globals['_PINGRESPONSE']._serialized_start=540
  _globals['_PINGRESPONSE']._serialized_end=571
  _globals['_LOGINSERVICE']._serialized_start=573
  _globals['_LOGINSERVICE']._serialized_end=653
  _globals['_LOGOUTSERVICE']._serialized_start=655
  _globals['_LOGOUTSERVICE']._serialized_end=739
  _globals['_TRANSFERSERVICE']._serialized_start=741
  _globals['_TRANSFERSERVICE']._serialized_end=833
  _globals['_UPLOADSERVICE']._serialized_start=835
  _globals['_UPLOADSERVICE']._serialized_end=919
  _globals['_TABLESERVICE']._serialized_start=921
  _globals['_TABLESERVICE']._serialized_end=1001
  _globals['_PINGSERVICE']._serialized_start=1003
  _globals['_PINGSERVICE']._serialized_end=1079
# @@protoc_insertion_point(module_scope)
